

services:
  backend:
    build: ./backend2
    ports:
      - "5000:3000"
    env_file:
      - ./backend2/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
