- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # Backend
      docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_BACKEND }}:latest

      docker stop backend || true
      docker rm backend || true

      docker run -d \
        --name backend \
        --restart unless-stopped \
        -p 3000:3000 \
        -e PORT=3000 \
        -e MONGO_URL="${{ secrets.MONGO_URL }}" \
        ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_BACKEND }}:latest

      # Frontend
      docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_FRONTEND }}:latest

      docker stop frontend || true
      docker rm frontend || true

      docker run -d \
        --name frontend \
        --restart unless-stopped \
        -p 80:80 \
        ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_FRONTEND }}:latest